
package com.in28minutes.students;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentPort", targetNamespace = "http://in28minutes.com/students")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentPort {


    /**
     * 
     * @param getStudentDetailsRequest
     * @return
     *     returns com.in28minutes.students.GetStudentDetailsResponse
     */
    @WebMethod(operationName = "GetStudentDetails")
    @WebResult(name = "GetStudentDetailsResponse", targetNamespace = "http://localhost:8080/students", partName = "GetStudentDetailsResponse")
    public GetStudentDetailsResponse getStudentDetails(
        @WebParam(name = "GetStudentDetailsRequest", targetNamespace = "http://localhost:8080/students", partName = "GetStudentDetailsRequest")
        GetStudentDetailsRequest getStudentDetailsRequest);

}
